# Import Library

In [1]:
import pandas as pd
import numpy as np

# Data Understanding

## Import Dataset dan Sumber, Nama, Format, serta Tujuan Dataset

In [2]:
data = pd.read_excel("Amazon.xlsx") # Membaca file excel

Sumber = gdrive (https://drive.google.com/drive/folders/1AWksosjsTfN-Y7sukK3GzkImtAqSpf_8)
Nama = Amazon.xlsx
Format = excel
Tujuan = Analisa Keuntungan Perusahaan Berdasarkan Kategori Produk, Lokasi, dan Pelanggan

In [3]:
amazon = pd.DataFrame(data) # Mengubahnya menjadi DataFrame
amazon

,Order ID,Order Date,Ship Date,EmailID,Geography,Category,Product Name,Sales,Quantity,Profit
0,CA-2013-138688,2013-06-13,2013-06-17,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,6.8714
1,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,14.1694
2,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,Newell 322,7.280,4,1.9656
3,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,Mitel 5320 IP Phone VoIP phone,907.152,4,90.7152
4,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,5.7825
...,...,...,...,...,...,...,...,...,...,...
3198,CA-2013-125794,2013-09-30,2013-10-04,MarisLaWare@gmail.com,"United States,Los Angeles,California",Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,15.2208
3199,CA-2014-121258,2014-02-27,2014-03-04,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,15.6332
3200,CA-2014-121258,2014-02-27,2014-03-04,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Phones,Aastra 57i VoIP phone,258.576,2,19.3932
3201,CA-2014-121258,2014-02-27,2014-03-04,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,13.3200
3202,CA-2014-119914,2014-05-05,2014-05-10,ChrisCortes@gmail.com,"United States,Westminster,California",Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,72.9480

Dataset berdimensi 3203 rows x 10 columns
Jumlah Baris = 3203
Jumlah Kolom = 10

Deskripsi Kolom :
Order ID: Kode unik untuk setiap transaksi
Order Date: Tanggal pelanggan melakukan pemesanan barang
Ship Date: Tanggal pesanan mulai dikirimkan kepada pelanggan
EmailID: Alamat email pelanggan yang melakukan transaksi
Geography: Informasi lokasi pengiriman yang mencakup Negara, Kota, dan Negara Bagian
Category: Kategori umum dari produk barang yang dibeli
Product Name: Nama spesifik dan deskripsi detail dari produk yang dibeli
Sales: Total nilai pendapatan atau omzet dari penjualan produk
Quantity: Jumlah barang yang dibeli oleh pelanggan
Profit: Nilai keuntungan bersih yang diperoleh perusahaan dari penjualan produk

In [4]:
amazon.info() # Untuk mengetahui jumlah baris dan kolom. Mengetahui missing value tiap kolom, nama nama kolom, dan tipe data tiap kolom

<class 'pandas.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      3203 non-null   str
 1   Order Date    3203 non-null   datetime64[us]
 2   Ship Date     3203 non-null   datetime64[us]
 3   EmailID       3203 non-null   str
 4   Geography     3203 non-null   str
 5   Category      3203 non-null   str
 6   Product Name  3203 non-null   str
 7   Sales         3203 non-null   float64
 8   Quantity      3203 non-null   int64
 9   Profit        3203 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(1), str(5)
memory usage: 605.8 KB

Terdapat 10 kolom
Dua kolom memiliki tipe data datetime, yaitu Order Date dan Ship Date
Lima kolom memiliki tipe data string, yaitu Order ID, EmailID, Geography, Category, dan Product Name 
Dua kolom memiliki tipe data float, yaitu Sales dan Profit
Satu kolom memiliki tipe data integer, yaitu Quantity
Semua kolom memiliki 3203 baris data, sehingga tidak terdapat missing value
Tipe data pada semua kolom sudah benar

In [5]:
amazon.describe() # Untuk mengetahui informasi statistik deskriptif pada kolom dengan tipe data integer dan float

,Order Date,Ship Date,Sales,Quantity,Profit
count,3203,3203,3203.000000,3203.000000,3203.000000
mean,2013-05-10 03:06:07.530440,2013-05-14 01:25:25.195129,226.493233,3.828910,33.849032
min,2011-01-07 00:00:00,2011-01-09 00:00:00,0.990000,1.000000,-3399.980000
25%,2012-05-22 00:00:00,2012-05-26 00:00:00,19.440000,2.000000,3.852000
50%,2013-07-22 00:00:00,2013-07-25 00:00:00,60.840000,3.000000,11.166400
75%,2014-05-23 00:00:00,2014-05-27 00:00:00,215.809000,5.000000,33.000400
max,2014-12-31 00:00:00,2015-01-06 00:00:00,13999.960000,14.000000,6719.980800
std,NaN,NaN,524.876877,2.260947,174.109081

Kolom Order Date, Ship Date, Sales, Quantity, dan Profit memiliki 3203 baris data, sehingga tidak ada missing value.

Sales memiliki rata rata penjualan sebesar 226,49 dan median sebesar 60,84, sehingga distribusi gaji karyawan cukup luas dan miring ke kanan. Standard deviasi sales sebesar 524,87, sehingga rentang gaji karyawan cukup lebar.

Quantity memiliki rata rata sebesar 3,82 dan median sebesar 3, sehingga distribusi kuantitas barang cukup dekat dan sedikit miiring ke kanan. Standard deviasi quantity sebesar 2,26, sehingga rentang kuantitas barang cukup sempit.

Profit memiliki rata rata sebesar 33,84 dan median sebesar 11,16, sehingga distribusi keuntungan tidak terlalu luas dan miring ke kanan. Standard deviasi profit sebesar 174,10, sehingga rentang keuntungan cukup lebar.

## Data Exploration

### Membuat Copy Dataset

In [6]:
amazon_copy = amazon.copy() # Membuat copy dataset

### Cek Inkonsistensi Data

In [7]:
order_id_unique = pd.DataFrame(amazon_copy["Order ID"].unique())
order_id_unique.to_excel("order_id_unique.xlsx") # Ekstrak unique item untuk diperiksa inkonsistensi
order_id_unique.rename(columns={0 : "Order_ID"}, inplace=True)
order_id_unique # Memanggil unique item untuk diperiksa inkonsistensi

            Order_ID
0     CA-2013-138688
1     CA-2011-115812
2     CA-2013-161389
3     CA-2011-167164
4     CA-2011-143336
...              ...
1606  CA-2014-137421
1607  US-2013-103674
1608  CA-2013-125794
1609  CA-2014-121258
1610  CA-2014-119914

[1611 rows x 1 columns]

In [8]:
email_id_unique = pd.DataFrame(amazon_copy["EmailID"].unique())
email_id_unique.to_excel("email_id_unique.xlsx") # Ekstrak unique item untuk diperiksa inkonsistensi
email_id_unique.rename(columns={0 : "Email_ID"}, inplace=True)
email_id_unique # Memanggil unique item untuk diperiksa inkonsistensi

                        Email_ID
0        DarrinVanHuff@gmail.com
1       BrosinaHoffman@gmail.com
2          IreneMaddox@gmail.com
3       AlejandroGrove@gmail.com
4    ZuschussDonatelli@gmail.com
..                           ...
681      TroyBlackwell@gmail.com
682          DanLawera@gmail.com
683          SungChung@gmail.com
684       MaribethDona@gmail.com
685          AnnePryor@gmail.com

[686 rows x 1 columns]

In [9]:
geography_unique = pd.DataFrame(amazon_copy["Geography"].unique())
geography_unique.to_excel("geography_unique.xlsx") # Ekstrak unique item untuk diperiksa inkonsistensi
geography_unique.rename(columns={0 : "Geography"}, inplace=True)
geography_unique # Memanggil unique item untuk diperiksa inkonsistensi

                                    Geography
0        United States,Los Angeles,California
1            United States,Seattle,Washington
2              United States,West Jordan,Utah
3      United States,San Francisco,California
4                     United States,Orem,Utah
..                                        ...
165            United States,Twin Falls,Idaho
166     United States,San Clemente,California
167           United States,Dublin,California
168  United States,San Luis Obispo,California
169             United States,Lodi,California

[170 rows x 1 columns]

In [10]:
category_unique = pd.DataFrame(amazon_copy["Category"].unique())
category_unique.to_excel("category_unique.xlsx") # Ekstrak unique item untuk diperiksa inkonsistensi
category_unique.rename(columns={0 : "Category"}, inplace=True)
category_unique # Memanggil unique item untuk diperiksa inkonsistensi

       Category
0        Labels
1   Furnishings
2           Art
3        Phones
4       Binders
5    Appliances
6        Tables
7       Storage
8   Accessories
9         Paper
10       Chairs
11    Fasteners
12     Supplies
13    Envelopes
14      Copiers
15    Bookcases
16     Machines

In [11]:
product_name_unique = pd.DataFrame(amazon_copy["Product Name"].unique())
product_name_unique.to_excel("product_name_unique.xlsx") # Ekstrak unique item untuk diperiksa inkonsistensi
product_name_unique.rename(columns={0 : "Product_Name"}, inplace=True)
product_name_unique # Memanggil unique item untuk diperiksa inkonsistensi

                                           Product_Name
0     Self-Adhesive Address Labels for Typewriters b...
1     Eldon Expressions Wood and Plastic Desk Access...
2                                            Newell 322
3                        Mitel 5320 IP Phone VoIP phone
4     DXL Angle-View Binders with Locking Rings by S...
...                                                 ...
1489   Eldon Econocleat Chair Mats for Low Pile Carpets
1490  Universal Recycled Hanging Pressboard Report B...
1491               Ibico Recycled Grain-Textured Covers
1492  Bush Andora Conference Table, Maple/Graphite G...
1493                           Avaya 5410 Digital phone

[1494 rows x 1 columns]

Berdasarkan hasil output dan pemeriksaan hasil ekstrak menjadi excel menggunakan AI, tidak terdapat inkonsistensi data seperti kapitalisasi, spasi, dan typo.

### Jumlah dan Persentase Missing Value

In [12]:
amazonnull = amazon_copy.isnull().sum() # Mencari jumlah missing value
amazonnullpercentage = amazonnull / len(amazon_copy) * 100 # Mencari persentase missing value

In [13]:
print(f"Jumlah missing value : \n{amazonnull}")
print(f"Persentase missing value : \n{amazonnullpercentage}")

Jumlah missing value :
Order ID        0
Order Date      0
Ship Date       0
EmailID         0
Geography       0
Category        0
Product Name    0
Sales           0
Quantity        0
Profit          0
dtype: int64
Persentase missing value :
Order ID        0.0
Order Date      0.0
Ship Date       0.0
EmailID         0.0
Geography       0.0
Category        0.0
Product Name    0.0
Sales           0.0
Quantity        0.0
Profit          0.0
dtype: float64

Tidak terdapat missing value pada dataset.

### Jumlah dan Persentase Duplicate Value

In [14]:
duplicate_all = amazon_copy.duplicated().sum() # Memeriksa jumlah duplicate value berdasarkan tiap baris
persent_duplicate_all = duplicate_all /len(amazon_copy)*100
print(f"Jumlah Baris yang duplikat = {duplicate_all}")
print(f"Persentase Baris yang duplikat = {persent_duplicate_all:.2f}%")

Jumlah Baris yang duplikat = 0
Persentase Baris yang duplikat = 0.00%

Tidak Terdapat Duplicate Value pada Tiap Baris.

### Encoder Kolom Kategori Untuk Periksa Outlier

In [15]:
from sklearn.preprocessing import LabelEncoder # Memanggil Library untuk LabelEncoder

In [16]:
le = LabelEncoder()

In [17]:
amazon_copy["Order_ID_Code"] = le.fit_transform(amazon_copy["Order ID"])
amazon_copy["EmailID_Code"] = le.fit_transform(amazon_copy["EmailID"])
amazon_copy["Geography_Code"] = le.fit_transform(amazon_copy["Geography"])
amazon_copy["Category_Code"] = le.fit_transform(amazon_copy["Category"])
amazon_copy["Product_Name_Code"] = le.fit_transform(amazon_copy["Product Name"])

### Jumlah dan Persentase Outlier Dengan IQR

In [18]:
'''Membuat Variabel Baru Untuk Mengambil Nama Kolom Dengan Tipe Data Numerikal'''
kolom_outlier = amazon_copy.select_dtypes(include=["int64", "float64"]).columns

In [19]:
kolom_outlier

Index(['Sales', 'Quantity', 'Profit', 'Order_ID_Code', 'EmailID_Code',
       'Geography_Code', 'Category_Code', 'Product_Name_Code'],
      dtype='str')

In [20]:
for i in kolom_outlier :
    Q1 = amazon_copy[i].quantile(0.25)
    Q3 = amazon_copy[i].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outlier = (amazon_copy[i] < lower) | (amazon_copy[i] > upper)
    jumlah_outlier = outlier.sum() # Mengetahui jumlah outlier pada kolom
    persentase_outlier = jumlah_outlier/len(outlier) * 100 # Mengetahui persentase outlier pada kolom
    print(f"Jumlah Outlier pada Kolom {i} : {jumlah_outlier}")
    print(f"Persentase Outlier pada Kolom {i} : {persentase_outlier:.2f}%\n")

Jumlah Outlier pada Kolom Sales : 368
Persentase Outlier pada Kolom Sales : 11.49%

Jumlah Outlier pada Kolom Quantity : 62
Persentase Outlier pada Kolom Quantity : 1.94%

Jumlah Outlier pada Kolom Profit : 465
Persentase Outlier pada Kolom Profit : 14.52%

Jumlah Outlier pada Kolom Order_ID_Code : 0
Persentase Outlier pada Kolom Order_ID_Code : 0.00%

Jumlah Outlier pada Kolom EmailID_Code : 0
Persentase Outlier pada Kolom EmailID_Code : 0.00%

Jumlah Outlier pada Kolom Geography_Code : 0
Persentase Outlier pada Kolom Geography_Code : 0.00%

Jumlah Outlier pada Kolom Category_Code : 0
Persentase Outlier pada Kolom Category_Code : 0.00%

Jumlah Outlier pada Kolom Product_Name_Code : 0
Persentase Outlier pada Kolom Product_Name_Code : 0.00%

Terdapat 11,5 persen data outlier pada kolom Sales.

Terdapat 2 persen data outlier pada kolom Quantity.

Terdapat 14,5 persen data outlier pada kolom Profit.

### Cek Distribusi Data Dengan Uji Shapiro-Wilk

In [21]:
from scipy.stats import shapiro

In [22]:
'''Membuat Variabel Baru Dari Dataset Copy Berupa Kolom Dengan Tipe Data Numerik'''
explore_numerik = amazon_copy[["Order_ID_Code", "EmailID_Code", "Geography_Code", "Category_Code", "Product_Name_Code", "Sales", "Quantity", "Profit"]]

In [23]:
for x in explore_numerik : 
    stat, p = shapiro(amazon_copy[x])
    print(f"p value Kolom {x} : {p:.3f}")
    if p >= 0.05 :
        print(f"Kolom {x} terdistribusi normal")
    else :
        print(f"Kolom {x} tidak terdistribusi normal\n")

p value Kolom Order_ID_Code : 0.000
Kolom Order_ID_Code tidak terdistribusi normal

p value Kolom EmailID_Code : 0.000
Kolom EmailID_Code tidak terdistribusi normal

p value Kolom Geography_Code : 0.000
Kolom Geography_Code tidak terdistribusi normal

p value Kolom Category_Code : 0.000
Kolom Category_Code tidak terdistribusi normal

p value Kolom Product_Name_Code : 0.000
Kolom Product_Name_Code tidak terdistribusi normal

p value Kolom Sales : 0.000
Kolom Sales tidak terdistribusi normal

p value Kolom Quantity : 0.000
Kolom Quantity tidak terdistribusi normal

p value Kolom Profit : 0.000
Kolom Profit tidak terdistribusi normal

Tidak terdapat data yang terdistribusi normal
Jika ingin melakukan uji statistik, dianjurkan uji statistik menggunakan Mann–Whitney test, Wilcoxon signed-rank test, ataupun Kruskal–Wallis test

### Insight Berdasarkan Hasil Eksplorasi

Tidak ada inkonsistensi data, tipe data pada tiap kolom sudah benar, tidak ada duplicate value, dan tidak ada missing value. Sehingga tidak ada penanganan inkonsistensi data, tipe data, duplicate value, dan missing value.

Terdapat outlier pada kolom Sales, Quantity, dan Profit. Penanganan yang dapat dilakukan adalah menkonfirmasi ulang kepada pemberi data. Jika data memang benar, maka dapat ditangani dengan transformasi log atau capping.

Data terdistribusi tidak normal sehingga perlu adanya konfirmasi kepada pemberi data mengenai kualitas data yang diberikan.

# Data Preparation

## Data Cleaning

### Cleaning Outlier

In [24]:
'''Penanganan Outlier Kolom Sales dengan Transformasi Capping'''
Q1_sales = amazon_copy["Sales"].quantile(0.25)
Q3_sales = amazon_copy["Sales"].quantile(0.75)
IQR_sales = Q3_sales - Q1_sales
lower_sales = Q1_sales - 1.5 * IQR_sales
upper_sales = Q3_sales + 1.5 * IQR_sales

amazon_copy["Sales_Cap"] = amazon_copy["Sales"].clip(lower_sales, upper_sales) # Transformasi Capping kolom Sales ke kolom Sales_Cap
Q1_sales_cap = amazon_copy["Sales_Cap"].quantile(0.25)
Q3_sales_cap = amazon_copy["Sales_Cap"].quantile(0.75)
IQR_sales_cap = Q3_sales_cap - Q1_sales_cap
lower_sales_cap = Q1_sales_cap - 1.5 * IQR_sales_cap
upper_sales_cap = Q3_sales_cap + 1.5 * IQR_sales_cap
outlier_sales_cap = (amazon_copy["Sales_Cap"] < lower_sales_cap) | (amazon_copy["Sales_Cap"] > upper_sales_cap)
jumlah_outlier_sales_cap = outlier_sales_cap.sum() # Mengetahui jumlah outlier pada kolom Sales_Cap
persentase_outlier_sales_cap = jumlah_outlier_sales_cap/len(amazon_copy) * 100 # Mengetahui persentase outlier pada kolom Sales_Cap
print(f"Jumlah Outlier pada Kolom Sales_Cap : {jumlah_outlier_sales_cap}")
print(f"Persentase Outlier pada Kolom Sales_Cap : {persentase_outlier_sales_cap}")

Jumlah Outlier pada Kolom Sales_Cap : 0
Persentase Outlier pada Kolom Sales_Cap : 0.0

Outlier kolom Sales berhasil ditangani dengan Capping.

In [25]:
'''Penanganan Outlier Kolom Quantity dengan Transformasi Log'''
amazon_copy["Quantity_Log"] = np.log(amazon_copy["Quantity"]) # Transformasi Log kolom Quantity ke kolom Quantity_Log
Q1_quantity_log = amazon_copy["Quantity_Log"].quantile(0.25)
Q3_quantity_log = amazon_copy["Quantity_Log"].quantile(0.75)
IQR_quantity_log = Q3_quantity_log - Q1_quantity_log
lower_quantity_log = Q1_quantity_log - 1.5 * IQR_quantity_log
upper_quantity_log = Q3_quantity_log + 1.5 * IQR_quantity_log
outlier_quantity_log = (amazon_copy["Quantity_Log"] < lower_quantity_log) | (amazon_copy["Quantity_Log"] > upper_quantity_log)
jumlah_outlier_quantity_log = outlier_quantity_log.sum() # Mengetahui jumlah outlier pada kolom Quantity_Log
persentase_outlier_quantity_log = jumlah_outlier_quantity_log/len(amazon_copy) * 100 # Mengetahui persentase outlier pada kolom Quantity_Log
print(f"Jumlah Outlier pada Kolom Quantity_Log : {jumlah_outlier_quantity_log}")
print(f"Persentase Outlier pada Kolom Quantity_Log : {persentase_outlier_quantity_log}")

Jumlah Outlier pada Kolom Quantity_Log : 0
Persentase Outlier pada Kolom Quantity_Log : 0.0

Outlier kolom Quantity berhasil ditangani dengan Transformasi Log.

In [26]:
'''Penanganan Outlier Kolom Profit dengan Transformasi Capping'''
Q1_profit = amazon_copy["Profit"].quantile(0.25)
Q3_profit = amazon_copy["Profit"].quantile(0.75)
IQR_profit = Q3_profit - Q1_profit
lower_profit = Q1_profit - 1.5 * IQR_profit
upper_profit = Q3_profit + 1.5 * IQR_profit

amazon_copy["Profit_Cap"] = amazon_copy["Profit"].clip(lower_profit, upper_profit) # Transformasi Capping kolom Profit ke kolom Profit_Cap
Q1_profit_cap = amazon_copy["Profit_Cap"].quantile(0.25)
Q3_profit_cap = amazon_copy["Profit_Cap"].quantile(0.75)
IQR_profit_cap = Q3_profit_cap - Q1_profit_cap
lower_profit_cap = Q1_profit_cap - 1.5 * IQR_profit_cap
upper_profit_cap = Q3_profit_cap + 1.5 * IQR_profit_cap
outlier_profit_cap = (amazon_copy["Profit_Cap"] < lower_profit_cap) | (amazon_copy["Profit_Cap"] > upper_profit_cap)
jumlah_outlier_profit_cap = outlier_profit_cap.sum() # Mengetahui jumlah outlier pada kolom Profit_Cap
persentase_outlier_profit_cap = jumlah_outlier_profit_cap/len(amazon_copy) * 100 # Mengetahui persentase outlier pada kolom Profit_Cap
print(f"Jumlah Outlier pada Kolom Profit_Cap : {jumlah_outlier_profit_cap}")
print(f"Persentase Outlier pada Kolom Profit_Cap : {persentase_outlier_profit_cap}")

Jumlah Outlier pada Kolom Profit_Cap : 0
Persentase Outlier pada Kolom Profit_Cap : 0.0

Outlier kolom Profit berhasil ditangani dengan Capping.

### Cek Kembali Tipe Data

In [27]:
amazon_copy.info() # Dapat digunakkan untuk cek tipe data

<class 'pandas.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           3203 non-null   str
 1   Order Date         3203 non-null   datetime64[us]
 2   Ship Date          3203 non-null   datetime64[us]
 3   EmailID            3203 non-null   str
 4   Geography          3203 non-null   str
 5   Category           3203 non-null   str
 6   Product Name       3203 non-null   str
 7   Sales              3203 non-null   float64
 8   Quantity           3203 non-null   int64
 9   Profit             3203 non-null   float64
 10  Order_ID_Code      3203 non-null   int64
 11  EmailID_Code       3203 non-null   int64
 12  Geography_Code     3203 non-null   int64
 13  Category_Code      3203 non-null   int64
 14  Product_Name_Code  3203 non-null   int64
 15  Sales_Cap          3203 non-null   float64
 16  Quantity_Log       3203 non-null   float64
 17  Profit_Cap         3203 non-null   float64
dtypes: datetime64[us](2), float64(5), int64(6), str(5)
memory usage: 805.9 KB

Tipe Data sudah benar.

## Dataset Sebelum dan Sesudah Cleaning

Sebelum cleaning, dataset awal tidak memiliki masalah pada missing value, duplicate value, tipe data, dan inkonsistensi data. Sehingga tidak ada penanganan. Namun dataset awal memiliki outlier pada kolom dengan tipe data float dan integer. Pada dataset yang sudah dicleaning, outlier ditangani dengan cara membuat kolom baru berdasarkan hasil dari transformasi log maupun capping dari kolom aslinya. Dataset yang sudah dicleaning sudah memiliki tipe data yang benar. Dataset yang sudah dicleaning tidak terdistribusi normal, sehingga jika ingin melakukan uji statistik, dianjurkan uji statistik menggunakan Mann–Whitney test, Wilcoxon signed-rank test, ataupun Kruskal–Wallis test

In [28]:
amazon.head()

,Order ID,Order Date,Ship Date,EmailID,Geography,Category,Product Name,Sales,Quantity,Profit
0,CA-2013-138688,2013-06-13,2013-06-17,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,6.8714
1,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,14.1694
2,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,Newell 322,7.280,4,1.9656
3,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,Mitel 5320 IP Phone VoIP phone,907.152,4,90.7152
4,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,5.7825

In [29]:
amazon_copy.head()

,Order ID,Order Date,Ship Date,EmailID,Geography,Category,Product Name,Sales,Quantity,Profit,Order_ID_Code,EmailID_Code,Geography_Code,Category_Code,Product_Name_Code,Sales_Cap,Quantity_Log,Profit_Cap
0,CA-2013-138688,2013-06-13,2013-06-17,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,6.8714,755,173,80,10,1164,14.6200,0.693147,6.8714
1,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,14.1694,68,96,80,9,464,48.8600,1.945910,14.1694
2,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,Newell 322,7.280,4,1.9656,68,96,80,2,915,7.2800,1.386294,1.9656
3,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,Mitel 5320 IP Phone VoIP phone,907.152,4,90.7152,68,96,80,13,884,510.3625,1.386294,76.7230
4,CA-2011-115812,2011-06-09,2011-06-14,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,5.7825,68,96,80,3,404,18.5040,1.098612,5.7825

## Dataset Siap Untuk Uji Statistik

In [30]:
amazon_statistik = amazon_copy[["Order_ID_Code", "Order Date", "Ship Date", "EmailID_Code", "Geography_Code", "Category_Code", "Product_Name_Code", "Sales_Cap", "Quantity_Log", "Profit_Cap"]]

In [31]:
'''Dataset Untuk Uji Statistik'''
amazon_statistik

,Order_ID_Code,Order Date,Ship Date,EmailID_Code,Geography_Code,Category_Code,Product_Name_Code,Sales_Cap,Quantity_Log,Profit_Cap
0,755,2013-06-13,2013-06-17,173,80,10,1164,14.6200,0.693147,6.8714
1,68,2011-06-09,2011-06-14,96,80,9,464,48.8600,1.945910,14.1694
2,68,2011-06-09,2011-06-14,96,80,2,915,7.2800,1.386294,1.9656
3,68,2011-06-09,2011-06-14,96,80,13,884,510.3625,1.386294,76.7230
4,68,2011-06-09,2011-06-14,96,80,3,404,18.5040,1.098612,5.7825
...,...,...,...,...,...,...,...,...,...,...
3198,692,2013-09-30,2013-10-04,433,80,0,870,36.2400,0.000000,15.2208
3199,1062,2014-02-27,2014-03-04,174,31,9,1237,91.9600,0.693147,15.6332
3200,1062,2014-02-27,2014-03-04,174,31,13,36,258.5760,0.693147,19.3932
3201,1062,2014-02-27,2014-03-04,174,31,12,754,29.6000,1.386294,13.3200
3202,1054,2014-05-05,2014-05-10,126,165,1,41,243.1600,0.693147,72.9480

## Dataset Siap Untuk Analisa

In [32]:
amazon_analisis = amazon_copy[["EmailID", "Geography", "Category", "Sales", "Quantity", "Profit"]] # Membuat dataset baru

In [33]:
'''Membuat Kolom Baru Berdasarkan Perhitungan'''
amazon_analisis["Modal"] = amazon_analisis["Sales"] - amazon_analisis["Profit"]
amazon_analisis["Harga Setiap Barang"] = amazon_analisis["Sales"] / amazon_analisis["Quantity"]
amazon_analisis["Modal Setiap Barang"] = amazon_analisis["Modal"] / amazon_analisis["Quantity"]

In [34]:
'''Dataset Untuk Analisa'''
amazon_analisis

,EmailID,Geography,Category,Sales,Quantity,Profit,Modal,Harga Setiap Barang,Modal Setiap Barang
0,DarrinVanHuff@gmail.com,"United States,Los Angeles,California",Labels,14.620,2,6.8714,7.7486,7.310,3.8743
1,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Furnishings,48.860,7,14.1694,34.6906,6.980,4.9558
2,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Art,7.280,4,1.9656,5.3144,1.820,1.3286
3,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Phones,907.152,4,90.7152,816.4368,226.788,204.1092
4,BrosinaHoffman@gmail.com,"United States,Los Angeles,California",Binders,18.504,3,5.7825,12.7215,6.168,4.2405
...,...,...,...,...,...,...,...,...,...
3198,MarisLaWare@gmail.com,"United States,Los Angeles,California",Accessories,36.240,1,15.2208,21.0192,36.240,21.0192
3199,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Furnishings,91.960,2,15.6332,76.3268,45.980,38.1634
3200,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Phones,258.576,2,19.3932,239.1828,129.288,119.5914
3201,DaveBrooks@gmail.com,"United States,Costa Mesa,California",Paper,29.600,4,13.3200,16.2800,7.400,4.0700
3202,ChrisCortes@gmail.com,"United States,Westminster,California",Appliances,243.160,2,72.9480,170.2120,121.580,85.1060

# Data Manipulation dan Analisa

## Filtering

### Jumlah Kerugian Dari Transaksi Yang Merugi Berdasarkan Kategori (Top 5)

In [35]:
'''Filtering berdasarkan profit yang kurang dari 0'''
amazon_analisis[amazon_analisis["Profit"] < 0].groupby("Category").agg(
    Total_Kerugian=("Profit", "sum"),
    Total_Sales=("Sales", "sum"),
    Total_Modal=("Modal", "sum")
).sort_values(by="Total_Kerugian", ascending=True).head(5)

           Total_Kerugian  Total_Sales  Total_Modal
Category
Tables         -5956.6671    23883.844   29840.5111
Machines       -5589.1288     4489.554   10078.6828
Bookcases      -4223.6424     8340.532   12564.1744
Chairs         -2390.3805    21361.208   23751.5885
Binders        -2224.9814     2975.385    5200.3664

Insight :
Saat menghitung transaksi yang rugi, kategori Tables merupakan kategori dengan jumlah kerugian tertinggi, disusul kategori Machines dan Bookcases. Hal ini terjadi akibat jumlah modal lebih besar dari jumlah sales. Apabila hal ini dibiarkan, maka perusahaan akan menanggung kerugian selama kedepan. Sehingga perlunya penetapan nilai sales yang lebih besar dari nilai modalnya

## Melakukan Grouping, Fungsi Agregasi, dan Sorting

### Kategori dengan keuntungan tertinggi ke terendah (Top 5)

In [36]:
'''Kategori dengan keuntungan tertinggi ke terendah (Top 5)'''
amazon_analisis.groupby("Category").agg(
    Total_Keuntungan = ("Profit", "sum"),
    Total_Kuantitas = ("Quantity", "sum")
).sort_values(by="Total_Keuntungan", ascending=False).head(5)

             Total_Keuntungan  Total_Kuantitas
Category
Copiers            19327.2351               88
Accessories        16484.5983             1032
Binders            16096.8016             1868
Paper              12119.2364             1702
Phones              9110.7426             1066

Insight :
Category Copiers memberikan profit paling tinggi dibandingkan kategori lainnnya. Namun dikarenakan ini adalah data di tahun 2011 - 2014 dan di tahun sekarang sudah era digitalisasi, maka harus divalidasi kembali apakah terdapat data baru dan apakah kategori Copiers masih menjadi kategori yang memberikan keuntungan terbesar

### Keuntungan Kategori Copiers Terbesar Berdasarkan Geography (Top 5)

In [37]:
'''Keuntungan Kategori Copiers Terbesar Berdasarkan Geography (Top 5)'''
amazon_analisis[amazon_analisis["Category"]=="Copiers"].groupby("Geography")["Profit"].agg(["sum"]).rename(columns={"sum" : "Total_Keuntungan"}).sort_values(by="Total_Keuntungan", ascending=False).head(5)

                                        Total_Keuntungan
Geography
United States,Seattle,Washington               8290.4449
United States,Los Angeles,California           3704.9333
United States,San Francisco,California         2132.9649
United States,Great Falls,Montana              1379.9770
United States,Des Moines,Washington            1151.9793

Insight :
Copiers memiliki keuntungan terbesar di lokasi United States, Seattle, Washington sebesar 8290.4449. Perbedaan nilai keuntungan ini signifikan jika dibandingkan lokasi lainnya. Lokasi ini memiliki banyak perkantoran dan instansi pemerintah, sehingga mengindikasikan bahwa Copiers banyak terjual dilokasi ini karena banyak kantor dan instansi pemerintah yang masih menggunakan kertas

### EmailID di United States,Seattle,Washington dengan profit tertinggi dari pembelian Copiers

In [38]:
'''EmailID di United States,Seattle,Washington dengan profit tertinggi dari pembelian Copiers'''
amazon_analisis[
    (amazon_analisis["Category"]=="Copiers") 
    & (amazon_analisis["Geography"]=="United States,Seattle,Washington")
    ].groupby("EmailID")["Profit"].agg(["sum"]).rename(columns={"sum" : "Total_Keuntungan"}).sort_values(by="Total_Keuntungan", ascending=False).head(5)

                       Total_Keuntungan
EmailID
RaymondBuch@gmail.com         6719.9808
FredHopkins@gmail.com         1480.4671
DanaKaydos@gmail.com            89.9970

Insight :
Pelanggan dengan email RaymondBuch@gmail.com merupakan penyumbang keuntungan terbesar dari pembelian Copiers di United States, Seattle, Washington. Sehingga dapat disarankan untuk menjalankan bisnis B2B dengan pelanggan tersebut dan menjadi supplier utama produk berkategori Copiers